import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    diarySidebar: [
        {
            type: "autogenerated", dirName: 'diary'
        }
    ],
    // 计算机基础理论导航
    computerSidebar: [
        {
            type: 'autogenerated', dirName: 'computer'
        },
    ],
    // 编程语言相关导航
    programSidebar: [
        {
            type: 'autogenerated', dirName: 'program'
        },
    ],
    // 数字电路
    digitalCircuit: [
        {
            type: 'autogenerated', dirName: 'computer/DigitalCircuit'
        },
    ],
    // 计算机组成原理
    computerComposition: [
        {
            type: 'autogenerated', dirName: 'computer/ComputerComposition'
        }
    ],
    // 计算机操作系统
    computerOperatingSystem: [
        {
            type: 'autogenerated', dirName: 'computer/ComputerOperatingSystem'
        }
    ],
    // 计算机网络
    computerNetwork: [
        {
            type: 'autogenerated', dirName: 'computer/ComputerNetwork'
        }
    ],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
